[workspace]
authors = ["google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "app"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.9.1,<4"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.13.1,<2"
pandas = ">=2.3.1,<3"
scikit-learn = ">=1.6.1,<2"
jupyterlab = ">=4.4.6,<5"
pip = ">=25.2,<26"
protobuf = "==3.20.3"
tensorflow = ">=2.9.1,<3"

[pypi-dependencies]
tensorflow = ">=2.9.0, <3"
tensorflow-gnn = ">=0.5.0, <0.6"
