[workspace]
authors = ["google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "spn-gnn-performance"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
tensorflow = ">=2.19.1,<3"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.16.3,<2"
pandas = ">=2.3.3,<3"
scikit-learn = ">=1.7.2,<2"
jupyterlab = ">=4.4.10,<5"
pip = ">=25.2,<26"

[pypi-dependencies]
tensorflow-gnn = ">=0.2.0"
